# Generated by Django 4.0.5 on 2022-06-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_staffprofile_is_lab_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='user_role',
            new_name='course_type',
        ),
    ]
