# Generated by Django 4.0.5 on 2022-06-23 07:38

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_remove_complaint_is_checked_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 23, 7, 38, 59, 912664, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
